name: React CI/CD

on:
  push:
    branches: [ "develop","main" ]
  pull_request:
    branches: [ "develop","main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node and cache
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install
        run: npm ci  

      - name: Test
        run: npm test -- --watchAll=false

      - name: Dependency Check
        run: npm audit || true 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: React build 
        run: npm run build

      - name: Upload files to S3
        run: ls  

