name: React CI/CD

on:
  push:
    branches: [ "develop","main" ]
  pull_request:
    branches: [ "develop","main" ]
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm ci  

      - name: Test
        run: npm test -- --watchAll=false

      - name: Dependency Check
        run: npm audit
  CD:
    runs-on: ubuntu-latest
    needs: CI
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build 
        run: docker build -t app .

      - name: downcase REPO
        run: |
          echo "REPOSITORY=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}  

      - name: Docker tag image
        run: |
          docker tag app ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
          docker tag app ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }}

      - name: Docker push
        run: docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}   

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}   